subfolder: EP
algo: 'ep'
override_prune_rate: True

# Architecture
arch: resnet20

# ===== Dataset ===== #
dataset: CIFAR10
name: resnet20_cifar10_sc

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
fine_tune_lr: 0.1
fine_tune_lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 150 #150 #150
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
init: signed_constant
mode: fan_in
nonlinearity: relu
prune_rate: 0.005
scale_fan: True
freeze_weights: True

# ===== Hardware setup ===== #
workers: 4
#gpu: 1

# ===== Checkpointing ===== #
checkpoint_at_prune: False #True

# ==== sanity check ==== #
skip_sanity_checks: True
