algo: 'ep'

# Architecture
arch: cResNet18

# ===== Dataset ===== #
dataset: CIFAR10
name: resnet18_cifar10_sc

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
init: signed_constant
mode: fan_in
nonlinearity: relu
prune_rate: 0.05
scale_fan: False
freeze_weights: True

# ===== Hardware setup ===== #
workers: 4
gpu: 1
